### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Switch from Tape to QUnit for testing

Closes issue #12.

- Tape doesn't work with `rdflib.js` currently
  (explicitly importing with `require('rdflib')` breaks the build
   since Rdflib doesn't work with Browserify).

- Using QUnit tests in the browser instead (this will also make
  TLS testing easier).

- Run tests with `npm test`, opens a web browser on `test/index.html`

- Added rdflib and qunit libs to `vendor/` folder

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Ready for review/merging.

**Comment by deiu** [comment]
Do you think we can add Travis integration at this point, or should that be in a different PR?

**Comment by dmitrizagidulin** [comment]
Different PR, I think. Let me see what's involved with QUnit on Travis. (And how the most important part works out - integration tests against an actual Solid server)

**Comment by dmitrizagidulin** [comment]
I'm happy to keep this PR open a bit longer, however, and add more commits / while that stuff is sorted out.

**Comment by deiu** [comment]
:+1:

**Pull request merged**
