### PR TITLE
Init typeregistry

### PR DESCRIPTION
**Pull request by deiu**
Closes issue #100.

- Improved the `absoluteUrl()` function
- Do not reload type indexes after patching
- Refactor existing type registry code
- Implement `initTypeRegistry*()` methods
- When registering types, if registry resources don't exist, they're created.

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Is this ready to review/merge?

**Comment by deiu** [comment]
Not yet

**Comment by dmitrizagidulin** [comment]
(Rebased this PR/branch on latest `master`).

**Comment by dmitrizagidulin** [comment]
Ok, registry handling code refactored, unit and integration tests added.
Ready for review & merge.

**Pull request merged**
